# Generated by ChatGPT

import re

import matplotlib.pyplot as plt
from mistletoe.block_token import BlockToken
from mistletoe.span_token import SpanToken

plt.rcParams["mathtext.fontset"] = "cm"


class InlineMath(SpanToken):

    pattern = re.compile(r"\$(.+?)\$")
    parse_group = 1

    def __init__(self, match):
        self.math = match.group(1)


class BlockMath(BlockToken):

    repr_attributes = BlockToken.repr_attributes + ("content", )

    @classmethod
    def start(cls, line):
        return line.strip() == "$$"

    @classmethod
    def check_interrupts_paragraph(cls, lines):
        return cls.start(lines.peek())

    @staticmethod
    def read(lines):
        next(lines)
        content_lines = []
        for line in lines:
            if line.strip() == "$$":
                break
            content_lines.append(line)
        return content_lines

    def __init__(self, content):
        self.content = "".join(content)
        self.children = []
