# Generated by ChatGPT

import io
import re

import matplotlib.pyplot as plt
from mistletoe.block_token import BlockToken
from mistletoe.span_token import SpanToken
from PIL import Image

plt.rcParams["mathtext.fontset"] = "cm"


class InlineMath(SpanToken):

    pattern = re.compile(r"\$(.+?)\$")
    parse_group = 1

    def __init__(self, match):
        self.math = match.group(1)


class BlockMath(BlockToken):

    repr_attributes = BlockToken.repr_attributes + ("content", )

    @classmethod
    def start(cls, line):
        return line.strip() == "$$"

    @classmethod
    def check_interrupts_paragraph(cls, lines):
        return cls.start(lines.peek())

    @staticmethod
    def read(lines):
        next(lines)
        content_lines = []
        for line in lines:
            if line.strip() == "$$":
                break
            content_lines.append(line)
        return content_lines

    def __init__(self, content):
        self.content = "".join(content)
        self.children = []


def render_equation(equation: str,
                    font_size: float,
                    *,
                    dpi: int = 100,
                    color: str = "#000000") -> Image.Image:
    """
    Render LaTeX text with dynamically adjusted figure size.
    """
    # Create a temporary figure to measure text size
    fig, ax = plt.subplots()
    ax.axis("off")
    text_obj = ax.text(0.5,
                       0.5,
                       equation,
                       fontsize=font_size,
                       ha="center",
                       va="center")
    fig.canvas.draw()
    renderer = fig.canvas.get_renderer()  # type: ignore
    bbox = text_obj.get_window_extent(renderer=renderer)
    plt.close(fig)

    # Compute dynamic figsize based on text size
    width_inches = bbox.width / dpi + 0.5  # Add some padding
    height_inches = bbox.height / dpi + 0.2

    # Create new figure with adjusted size
    fig, ax = plt.subplots(figsize=(width_inches, height_inches), dpi=dpi)
    ax.axis("off")
    ax.text(0.5, 0.5, equation, fontsize=font_size, ha="center", va="center")
    ax.patch.set_facecolor(color)
    fig.canvas.draw()

    buf = io.BytesIO()
    plt.savefig(buf, format="png", bbox_inches="tight", transparent=True)
    buf.seek(0)
    image = Image.open(buf)
    plt.close(fig)
    return image
